### ISSUE TITLE
Using export setting environment

### ISSUE THREAD

**Issue by nylon7** [kvm-riscv/howto#1]
2. Build OpenSBI Firmware with Hypervisor Extension Support
CROSS_COMPILE=riscv64-unknown-linux-gnu- ->export CROSS_COMPILE=riscv64-unknown-linux-gnu-

3. Build Common Host & Guest Linux Kernel Image
ARCH=riscv  ->export ARCH=riscv
CROSS_COMPILE=riscv64-unknown-linux-gnu-  -> export CROSS_COMPILE=riscv64-unknown-linux-gnu-

4. Add libfdt library to CROSS_COMPILE SYSROOT directory
ARCH=riscv  ->  export ARCH=riscv
CROSS_COMPILE=riscv64-unknown-linux-gnu-  ->  export CROSS_COMPILE=riscv64-unknown-linux-gnu-

5. Build KVMTOOL
ARCH=riscv  ->  export ARCH=riscv
CROSS_COMPILE=riscv64-unknown-linux-gnu-  ->  export CROSS_COMPILE=riscv64-unknown-linux-gnu-

6. Build Host RootFS containing KVMTOOL and Guest Linux
ARCH=riscv  ->  export ARCH=riscv
CROSS_COMPILE=riscv64-unknown-linux-gnu-  ->  export CROSS_COMPILE=riscv64-unknown-linux-gnu-

**Comment by nylon7** [comment]
Hello @avpatel :

Thank you for your guideline so that I can boot up "RSICV-KVM".

As I see it, we should export setting environment?

**Comment by avpatel** [comment]
Thanks, I will update wiki instructions like you suggested.

Regards,
Anup

**Comment by nylon7** [comment]
Thank for your feedback

**Comment by avpatel** [comment]
Let's keep this issue open until I have updated the wiki.

Regards,
Anup

**Comment by avpatel** [comment]
I have fixed the wiki page. Closing this issue.

Regards,
Anup
