### ISSUE TITLE
About Wiki Home page.

### ISSUE THREAD

**Issue by Du-Chao** [kvm-riscv/howto#10]
It is mentioned that "The Kernel Based Virtual Machive (KVM) is an open-source Type2 hypervisor ..." in https://github.com/kvm-riscv/howto/wiki , should it be Type1 hypervisor ?

**Comment by Du-Chao** [comment]
KVM converts Linux into a type-1 hypervisor, to be precise.

**Comment by avpatel** [comment]
Update the wiki page.
