### ISSUE TITLE
Incorrect cross compiler name

### ISSUE THREAD

**Issue by AxFrancois** [kvm-riscv/howto#11]
Greetings,

I just followed the wiki guide to build the KVM RISCV64 on QEMU, there is a small error/changes that need to be addressed : `export CROSS_COMPILE=riscv64-unknown-linux-gnu-` should be `export CROSS_COMPILE=riscv64-linux-gnu-` on part 2, 3, 4 and 5. 
Apart that, it worked flawlessly, thanks a lot !

**Comment by avpatel** [comment]
`CROSS_COMPILE=riscv64-unknown-linux-gnu-` is the most popular choice hence we used it in wiki pages.
