### ISSUE TITLE
How to use network

### ISSUE THREAD

**Issue by GToad** [kvm-riscv/howto#6]
Sorry, but I cannot use network in host & guest. 
I add "-device virtio-net-device,netdev=usernet -netdev user,id=usernet,hostfwd=tcp::10000-:22" for QEMU and still not work. Can someone help me for the network for host & guest?

**Comment by avpatel** [comment]
Add `-device virtio-net-device,netdev=eth0 -netdev user,id=eth0` to QEMU command-line.
