### ISSUE TITLE
Add a step during Linux host and guest build to enable KVM by default

### ISSUE THREAD

**Issue by rsahita** [kvm-riscv/howto#7]
should add the step to enable KVM by default in the Linux build step in the kvm config.

**Comment by avpatel** [comment]
From Linux-5.16-rc2, we will have KVM RISC-V built as module using defconfigs. I have updated steps in wiki pages to reflect this.

Try the updated steps with Linux-5.16-rc2 or higher and let me know if you face any issue.

**Comment by rsahita** [comment]
Makes sense. Thanks for adding the additional steps!
