### ISSUE TITLE
Is it impossible to build kvmtool

### ISSUE THREAD

**Issue by pashaniaosi** [kvm-riscv/howto#8]
hello, when I follow the Step5("KVM RISCV64 on QEMU") to build kvmtool, there are something wrong:
```bash
Makefile:363: Skipping optional libraries: bfd zlib aio
  CC       builtin-balloon.static.o
In file included from include/linux/rbtree.h:32,
                 from include/kvm/devices.h:4,
                 from include/kvm/pci.h:10,
                 from include/kvm/vfio.h:6,
                 from include/kvm/kvm-config.h:5,
                 from include/kvm/kvm.h:6,
                 from builtin-balloon.c:9:
include/linux/kernel.h:5:10: fatal error: asm/kernel.h: No such file or directory
    5 | #include "asm/kernel.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:477: builtin-balloon.static.o] Error 1
```
so, I list all the files in `riscv/include/asm`:
```bash
kvm.h
```
the file `kernel.h` is not found in the directory(`riscv/include/asm`), but it can be found in other directories(`mips/include/asm, x86/include/asm`). So, I doubt the git repository of kvmtool lost the header file kernel.h of riscv.
![image](https://user-images.githubusercontent.com/19612248/168340307-52151912-29e4-4686-8cc5-a93a787ba64a.png)
I try to fix the error by deleting this line (`#include "asm/kernel.h"`). It really works, but whether would affect the result of `make`?

**Comment by avpatel** [comment]
Please export "ARCH=riscv" and "CROSS_COMPILE" environment variable before building.

**Comment by pashaniaosi** [comment]
> Please export "ARCH=riscv" and "CROSS_COMPILE" environment variable before building.

I have done this before building. According to the error message, it lost a header file "kernel.h" in the directory (`riscv/include/asm`) and I can't find this file in the [kvmtool repository](https://git.kernel.org/pub/scm/linux/kernel/git/will/kvmtool.git/tree/riscv/include/asm).

**Comment by avpatel** [comment]
KVMTOOL only includes UAPI headers exported from the kernel.

Regards,
Anup

**Comment by pashaniaosi** [comment]
The newest commit had fixed this issue.
![image](https://user-images.githubusercontent.com/19612248/172011072-a9e4b955-ee9f-489b-96ed-07c7320e5d2b.png)
The [official repository](https://git.kernel.org/pub/scm/linux/kernel/git/will/kvmtool.git/) had added missing `asm/kernel.h` header.
