### ISSUE TITLE
spike can't boot the latest kernel

### ISSUE THREAD

**Issue by walimis** [kvm-riscv/howto#9]
The latest spike can't boot the latest kernel now, but qemu can do. Can anyone encounter the same issue?

kernel commit:
commit 8c23f235a6a8ae43abea215812eb9d8cf4dd165e (HEAD -> master, origin/master, origin/HEAD)
Merge: 6a0a17e6c6d1 b0d473185ba8
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Fri Jun 24 17:01:31 2022 -0700

    Merge tag 'gpio-fixes-for-v5.19-rc4' of git://git.kernel.org/pub/scm/linux/kernel/git/brgl/linux

spike commit:
commit ac466a21df442c59962589ba296c702631e041b5 (HEAD -> master, origin/master, origin/HEAD)
Merge: 656fa5ac 7d943d74
Author: Andrew Waterman <andrew@sifive.com>
Date:   Tue Jun 7 13:20:52 2022 -0700

    Merge pull request #1027 from riscv-software-src/fix-1022

    Fix #1022 by removing need to mask insn_t bits

opensbi commit:
commit 4489876e933d8ba0d8bc6c64bae71e295d45faac (HEAD -> master, tag: v1.1, origin/master, origin/HEAD)
Author: Anup Patel <apatel@ventanamicro.com>
Date:   Sat Jun 25 09:12:10 2022 +0530

    include: Bump-up version to 1.1

spike hangs at booting opensbi now:

$ ./riscv-isa-sim/spike -m1024 --isa rv64gch --kernel ./build-riscv64/arch/riscv/boot/Image --initrd ./rootfs_kvm_riscv64.img opensbi/build/platform/generic/firmware/fw_jump.elf

OpenSBI v1.1
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|____/_____|
        | |
        |_|

Platform Name             : ucbbar,spike-bare
Platform Features         : medeleg
Platform HART Count       : 1
Platform IPI Device       : aclint-mswi
Platform Timer Device     : aclint-mtimer @ 10000000Hz
Platform Console Device   : htif
Platform HSM Device       : ---
Platform Reboot Device    : htif
Platform Shutdown Device  : htif
Firmware Base             : 0x80000000
Firmware Size             : 284 KB
Runtime SBI Version       : 1.0

Domain0 Name              : root
Domain0 Boot HART         : 0
Domain0 HARTs             : 0*
Domain0 Region00          : 0x0000000002080000-0x00000000020bffff (I)
Domain0 Region01          : 0x0000000002000000-0x000000000207ffff (I)
Domain0 Region02          : 0x0000000080000000-0x000000008007ffff ()
Domain0 Region03          : 0x0000000000000000-0xffffffffffffffff (R,W,X)
Domain0 Next Address      : 0x0000000080200000
Domain0 Next Arg1         : 0x0000000082200000
Domain0 Next Mode         : S-mode
Domain0 SysReset          : yes

Boot HART ID              : 0
Boot HART Domain          : root
Boot HART Priv Version    : v1.12
Boot HART Base ISA        : rv64imafdch
Boot HART ISA Extensions  : none
Boot HART PMP Count       : 16
Boot HART PMP Granularity : 4
Boot HART PMP Address Bits: 54
Boot HART MHPM Count      : 0
Boot HART MIDELEG         : 0x0000000000001666
Boot HART MEDELEG         : 0x0000000000f0b509

**Comment by avpatel** [comment]
Latest Linux has earlycon=sbi and SBI HVC console disabled by default. Try enabling these options manually.

We need PLIC+UART support in Spike to support running the latest Linux out-of-box. I had already raised PR for Spike more than 6 months back but it's not merged yet.

Regards,
Anup

**Comment by avpatel** [comment]
Enable the following options in Linux manually:
CONFIG_SERIAL_EARLYCON_RISCV_SBI
CONFIG_HVC_RISCV_SBI

Regards,
Anup

**Comment by walimis** [comment]
> Enable the following options in Linux manually: 
>CONFIG_SERIAL_EARLYCON_RISCV_SBI 
>CONFIG_HVC_RISCV_SBI 

Thanks, with CONFIG_RISCV_SBI_V01=y and above configs, now spike can print booting message.
